name: Run KBC Quiz
on: [push, pull_request]

jobs:
  run-quiz:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install Tkinter (for GUI)
      run: sudo apt-get install python3-tk -y
        
    - name: Run CLI Quiz
      run: |
        # For file with spaces, use quotes and backslashes
        python "Kaun bny ga crore patti.py" <<< "b c d b d a"
        
    - name: Run GUI Test
      run: |
        xvfb-run -a python "Kaun bny ga crore patti.py"
